use_frameworks!

target 'ALKit_Example' do
    #pod 'ALKit', :path => '../'
    pod 'ALKit', :git => 'https://github.com/rvndios/ALKitTest.git', :tag => '1.0'

  target 'ALKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
